include:
  - remote: https://raw.githubusercontent.com/ika-rwth-aachen/docker-ros/main/.gitlab-ci/docker-ros.yml

variables:
  IMAGE_TAG: ros
  BASE_IMAGE: rwthika/ros:latest
  COMMAND: roslaunch mqtt_client standalone.launch
  PLATFORM: amd64,arm64
  TARGET: dev,run
  ENABLE_INDUSTRIAL_CI: 'true'
