name: bloom-release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  bloom-release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: at-wat/bloom-release-action@v0
        with:
          ros_distro: humble jazzy kilted rolling
          github_token_bloom: ${{ secrets.GH_TOKEN_FOR_BLOOM_RELEASE }}
          github_user: lreiher
          git_user: Lennart Reiher
          git_email: lennart.reiher@ika.rwth-aachen.de
          release_repository_push_url: https://github.com/ros2-gbp/mqtt_client-release.git
          open_pr: false
